#!/usr/bin/env python

# word-wrap 0.1

import sys
from os.path import basename

def print_help():
	print("usage: " + basename(sys.argv[0]) + """ [options] < input_text_file
Word wraps text on your terminal screen.

Example 1: ww < README
Example 2: echo Hello, world! | ww

Options:
  -w <term_width>   set terminal width
                    (default is 80)
  -t <tab_width>    set tab width
                    (default is 8)
  -o <offset>       pass in the number of characters already on the first line
                    (default is 0)
  -h                print this help message
  -v                print version number

Created by Hasan N. Genc""")

def print_version():
	print("0.1")

if __name__ == "__main__":
	special_chars = " \n\t-"

	term_width = 80
	tab_width = 8
	offset = 0

	if "-h" in sys.argv or "--help" in sys.argv:
		print_help()
		exit()
	if "-v" in sys.argv or "--version" in sys.argv:
		print_version()
		exit()
	if "-w" in sys.argv:
		term_width = int(sys.argv[sys.argv.index("-w") + 1])
	if "-t" in sys.argv:
		tab_width = int(sys.argv[sys.argv.index("-t") + 1])
	if "-o" in sys.argv:
		offset = int(sys.argv[sys.argv.index("-o") + 1])

	space_left = term_width - offset

	c = sys.stdin.read(1)

	while c:
		if c not in special_chars:
			word = ""
			while c != "" and c not in special_chars:
				word += c
				c = sys.stdin.read(1)

			if len(word) <= space_left:
				sys.stdout.write(word)
				space_left -= len(word)

			elif len(word) <= term_width:
				sys.stdout.write("\n" + word)
				space_left = term_width - len(word)

			else:
				sys.stdout.write(word)
				space_left = (len(word) - space_left) % term_width

		else:
			if c == " ":
				if space_left > 0:
					sys.stdout.write(c)
					space_left -= 1

			elif c == "\n":
				sys.stdout.write(c)
				space_left = term_width

			elif c == "\t":
				if space_left >= tab_width:
					new_tab_width = tab_width - ((term_width-space_left) % tab_width)
					sys.stdout.write(" " * new_tab_width)
					space_left -= new_tab_width
				else:
					space_left = 0

			elif c == "-":
				sys.stdout.write(c)
				if space_left == 0:
					space_left = term_width
				space_left -= 1
			
			c = sys.stdin.read(1)
